python:
  - "2.7"
  - "2.6"
  - "3.2"
before_install:
  - make build-depends
script:
  - make test
  - make setup
  - make package
after_success:
  - >
    if [ "$TRAVIS_BRANCH" == "master" -a "$TRAVIS_EVENT_TYPE" == "push" -a "$TRAVIS_PULL_REQUEST" == "false" ]; then
      echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin ;
      echo "Pushing built Docker Image to: $TRAVIS_REPO_SLUG" ;
      make ship ;
    fi ;
  - "[ -e \"~/.docker/config.json\" ] && shred -n 30 -u -z ~/.docker/config.json"
